name: Continuous Integration and Deployment

on:
  push:
    branches: "main"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --password=root_password" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3.11"
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Key
        run: php artisan key:generate

      - name: Clear Config and Cache
        run: |
          php artisan config:clear
          php artisan route:clear

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install npm Dependencies
        run: |
          npm install

      - name: Build Frontend Assets
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: public/

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_FE }}
          username: ${{ secrets.FTP_USERNAME_FE }}
          password: ${{ secrets.FTP_PASSWORD_FE }}
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/.dist/**
            **/.github/**
            **/vendor/**
            **/node_modules/**
            Daskomku.zip
            daskomrec25.zip
            node_modules.zip
            vendor.zip
            public.zip
            
      - name: 📂 Deploy Build Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          exclude: |
            .env
            **/.git*
            **/.git*/**
            **/.dist/**
            **/.github/**
            **/app/**
            **/bootstrap/**
            **/config/**
            **/database/**
            **/node_modules/**
            **/resources/**
            **/routes/**
            **/storage/**
            **/tests/**
            **/vendor/**
            .editorconfig
            .env.example
            .gitattributes
            .gitignore
            artisan
            composer.json
            composer.lock
            Daskomku.zip
            daskomrec25.zip
            node_modules.zip
            package-lock.json
            package.json
            phpunit.xml
            pnpm-lock.yaml
            postcss.config.js
            public.zip
            README.md
            tailwind.config.js
            vendor.zip
            vite.config.js


